---
title: "C04_assignment.Rmd"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("/home/isgott28/ColbyForecasting/setup.R")
```



```{r load_data,echo=FALSE}
cfg = read_configuration(scientificname = "Cetorhinus Maximus", version = "v1")
model_input = read_model_input(scientificname = "Cetorhinus Maximus", 
                               version = "v1",
                               log_me = c("depth", "Xbtm")) |>
  dplyr::mutate(month = month_as_number(.data$month)) |>
  select(all_of(c("class", cfg$keep)))
```


```{r initial_split,echo=FALSE}
model_input_split = spatial_initial_split(model_input, 
                        prop = 1 / 5,     # 20% for testing
                        strategy = spatial_block_cv) # see ?spatial_block_cv
model_input_split
```



```{r initial_split_plot}
autoplot(model_input_split)
```

```{r cv_training}
tr_data = training(model_input_split)
cv_tr_data <- spatial_block_cv(tr_data,
  v = 5,     
  cellsize = grid_cellsize(model_input),
  offset = grid_offset(model_input) + 0.00001
)
autoplot(cv_tr_data)
```


```{r plot_wflow}
autoplot(wflow)
```


```{r model_fit_confmat}
model_fit_confmat(model_fits)
```



```{r model_fit_roc_auc}
model_fit_roc_auc(model_fits)
```




```{r rf_splits}
autoplot(rf$splits[[1]])
```



```{r rf_metrics}
rf$.metrics[[1]]
```



```{r rf_preds}
rf$.predictions[[1]]
```




```{r rf_workflow}
rf$.workflow[[1]]
```



```{r pd_plot}
model_fit_pdp(model_fits, wid = "default_btree", title = "Boosted Tree")
```



